### ISSUE TITLE
Installing pyesasky currently fails because required library 'request' has gone missing

### ISSUE THREAD

**Issue by jonashaase** [esdc-esac-esa-int/pyesasky#11]
Hi there

When I am trying to install pyesasky in a clean docker container (miniconda python installation)
I get the following error:

`idies@85a5e40983c2:~$ pip install pyesasky==1.4.2
Collecting pyesasky==1.4.2
  Downloading pyesasky-1.4.2-py2.py3-none-any.whl (5.2 MB)
     |████████████████████████████████| 5.2 MB 2.3 MB/s 
Collecting flask-cors
  Downloading Flask_Cors-3.0.8-py2.py3-none-any.whl (14 kB)
Collecting lxml
  Downloading lxml-4.5.2-cp37-cp37m-manylinux1_x86_64.whl (5.5 MB)
     |████████████████████████████████| 5.5 MB 6.2 MB/s 
Requirement already satisfied: six in ./miniconda3/lib/python3.7/site-packages (from pyesasky==1.4.2) (1.15.0)
Collecting configparser
  Downloading configparser-5.0.0-py3-none-any.whl (22 kB)
Requirement already satisfied: traitlets in ./miniconda3/lib/python3.7/site-packages (from pyesasky==1.4.2) (4.3.3)
Requirement already satisfied: qtpy in ./miniconda3/lib/python3.7/site-packages (from pyesasky==1.4.2) (1.9.0)
Requirement already satisfied: ipywidgets>=7.5.1 in ./miniconda3/lib/python3.7/site-packages (from pyesasky==1.4.2) (7.5.1)
ERROR: Could not find a version that satisfies the requirement request (from pyesasky==1.4.2) (from versions: none)
ERROR: No matching distribution found for request (from pyesasky==1.4.2)
`

On an older system it works because the request/post/get libraries still are in the site-packages. 
The github repo and pypi URLs in the correspondin metadata files are all dead, so it looks like this module has disappeared?

`idies@fb0c9afcafc7:~/miniconda3/lib/python3.8/site-packages$ cat request-2019.4.13.dist-info/METADATA 
Metadata-Version: 2.1
Name: request
Version: 2019.4.13
Summary: UNKNOWN
Home-page: https://github.com/looking-for-a-job/request.py
License: UNKNOWN
Keywords: request http
Platform: UNKNOWN
Description-Content-Type: text/markdown
Requires-Dist: get
Requires-Dist: post
Requires-Dist: setuptools

[![](https://img.shields.io/pypi/pyversions/request.svg?longCache=True)](https://pypi.org/project/request/)

#### Installation
```bash
$ [sudo] pip install request
```

#### Examples
```python
>>> import request

>>> request.REQUEST
{...}
```

#### Links
+   [GET](https://pypi.org/project/get/)
+   [POST](https://pypi.org/project/post/)
+   [REQUEST](https://pypi.org/project/request/)

<p align="center">
    <a href="https://pypi.org/project/python-readme-generator/">python-readme-generator</a>
</p>

` 

cheers
Jonas

**Comment by mattiaswangblad** [comment]
Hi Jonas,

Thanks for finding this, I just came back from holiday so sorry for not answering faster. It was actually a typo in the requirements. The packages used is _requests_ instead of _request_ which still does exists.

I've updated setup.py so the installation should look for the correct package now.
