### ISSUE TITLE
Git merge cruft in README

### ISSUE THREAD

**Issue by danielballan** [esdc-esac-esa-int/pyesasky#2]
I notice that the README.md currently has some git merge cruft as in:

```
<<<<<<< HEAD Jupyter and node.js
```

I would propose a fix via PR but I'm not sure I have the context to resolve it properly.

**Comment by mattiaswangblad** [comment]
Hi Dan,

Thanks for noticing, it's fixed and should be clearer now. Please give more feedback if you are struggling with anything or have some features you would like to add.
