### ISSUE TITLE
GitHub releases / tags

### ISSUE THREAD

**Issue by teake** [esdc-esac-esa-int/pyesasky#3]
I just saw @mattiaswangblad's presentation at IVOA -- cool stuff you're doing here!

But I noticed the GitHub releases and tags lag a bit behind the PyPI releases. Could I ask you to keep them up to date? I'm asking because I can foresee building a ocnda-forge package for pyESASky, and for that you need tagged GitHub releases. Thanks!

**Comment by mattiaswangblad** [comment]
@teake 
Thanks for the subtle reminder :). I've updated the latest release/tag to the latest (basically first pip version)
